use_frameworks!

platform :ios, '12.0'

target 'PureDataKit_Example' do
  pod 'PureDataKit', :path => '../'
#  pod 'PureDataKit', :git => 'https://github.com/EvansPie/PureDataKit.git', :tag => '0.1.3'

  target 'PureDataKit_Tests' do
    inherit! :search_paths

    
  end
end
